name: CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    
    - name: Snapcraft
      uses: snapcore/action-build@v1

    - uses: actions/upload-artifact@v2
      with:
        name: gstm_1.3.7_amd64.snap
        path: gstm_1.3.7_amd64.snap
